# Generated by Django 5.0.6 on 2024-06-04 19:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=30)),
                ('incridients', models.TextField()),
                ('image', models.TextField()),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('price', models.PositiveIntegerField()),
                ('kitchen_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_api.kitchen')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(8)])),
                ('image', models.TextField(default='https://static.tildacdn.com/tild3133-6461-4762-b763-393238646435/1_9e9CY6nDatrFlVkDHW.png')),
                ('home_adress', models.TextField()),
                ('cart', models.ManyToManyField(blank=True, to='food_api.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_at', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('1', 'В обработке'), ('2', 'Готовится '), ('3', 'Доставляется'), ('4', 'Доставлен')], max_length=100)),
                ('total_price', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='food_api.user')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='food_api.user')),
            ],
        ),
    ]
